dist: xenial
group: edge
sudo: required
language: python
jdk:
- oraclejdk8
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
- JENKINS_VERSION=stable
- JENKINS_VERSION=latest
install:
- pip install tox-travis
- python setup.py -q sdist bdist_wheel
script:
- tox
jobs:
  include:
  - stage: test
    script: tox
  - stage: release
    script: skip
    deploy:
      user: lechat
      password:
        secure: Sx99ZHXkGAxWYn2mDz3U9RQg6Yjta22Tu/9ndXxKIAbyGaFn9jPmpYNB2oNu7/6djlfmNsN9cvGze3FghyToW7YHwRC7pSCVxVlqJb+fFOLbhxJeh2RgmUQRqlhWSs/xjGypNdMkNosuAv08UZr1HX1wgYF3rWnAZFDlDsQeayU=
      on:
        repo: pycontribs/jenkinsapi
        tags: true
      provider: pypi
      distributions: "sdist bdist_wheel"
      skip_cleanup: true
