dist: trusty
group: edge
sudo: required
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- JENKINS_VERSION=stable
- JENKINS_VERSION=latest
before_install:
- jdk_switcher use oraclejdk8
install:
- pip install tox-travis
- python setup.py -q sdist bdist_wheel
script:
- tox
jobs:
  include:
    - stage: test
      script: tox
    - stage: release
      script: skip
      deploy:
        on:
          repo: pycontribs/jenkinsapi
          tags: true
        provider: pypi
        user: lechat
        password:
            secure: "QH20CSAJtRE05y+ayzQBjrGnbtErKD+JbXNXk9ULW7RhSZphfzxCwt1HYdwm3FEziGIUKT+H/s43uXs3OqweltkCNjYMMcTfQQCEKpcuxStEUaJTrIwdgH29TW6TgycBHJemg9wet4NVFpoya68pWFaZt7K1kLUUkzk3MFNP43k="
        distributions: "sdist bdist_wheel"
        skip_cleanup: true
