language: python
python:
- '2.7'
- '3.4'
- '3.5'
env:
- JENKINS_VERSION=1.x
- JENKINS_VERSION=2.x
jdk:
- oraclejdk8
install:
- pip install -r requirements/dev-requirements.txt
- python setup.py develop
script:
- make lint
- make coverage
after_success:
   - codecov
